product.pid = 101
product.pname = santoor
product.price = 40
product.qty = 20%
product.location = chennai

product.pid = 102
product.pname = lux soap
product.price = 60
product.qty = 18%
product.location = hyderabad
